### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by taking** [kfsoftware/hlf-operator#33]
Hello.
Is it possible to use couchdb when creating a peer?
and how to set etcdraft with kubectl hlf?

**Comment by dviejokfs** [comment]
Hi @taking 

You can specify this property when defining the YAML for the peer:
```yaml
# couchdb credentials
  couchdb:
    password: couchdb
    user: couchdb
  stateDb: couchdb
```

If you set the previous properties in the YAML, the operator will create a CouchDB as a sidecar for the peer at creation time.

Note that you can't change the world state database after the peer has been initialized:
![image](https://user-images.githubusercontent.com/84456338/148546281-63c1c021-3d57-49eb-a480-5a400d98ab96.png)

More info here:
https://hyperledger-fabric.readthedocs.io/en/release-2.3/couchdb_as_state_database.html

Specifying CouchDB as a world state database is something to be added for the documentation for the next release; thanks for pointing it out!
