### ISSUE TITLE
How to set level or couch db?

### ISSUE THREAD

**Issue by nkaramolegos** [kfsoftware/hlf-operator#41]
How can I set the desired database?

**Comment by dviejokfs** [comment]
Hi @nkaramolegos 

You can configure couchdb by setting the following property in the yaml:
```yaml
  couchdb:
    externalCouchDB: null
    password: couchdb
    user: couchdb
```

And then setting the stateDb property to `couchdb`:

```yaml
stateDb: couchdb
```

When creating the peer, you can pass the `--statedb` flag with the value `couchdb` in order to create a peer with CouchDB instead of leveldb. Note that you cannot switch the state database for an existing peer, if you want to switch to couchdb you must create new peers.

[https://hyperledger-fabric.readthedocs.io/en/release-2.3/couchdb_as_state_database.html](https://hyperledger-fabric.readthedocs.io/en/release-2.3/couchdb_as_state_database.html)

![image](https://user-images.githubusercontent.com/84456338/152058020-ad9d2bb3-29b4-444c-afaa-8ba2c48d7b4a.png)

**Comment by nkaramolegos** [comment]
thank you. Can you specify the yaml file? Is  [this](https://github.com/kfsoftware/hlf-operator/blob/f3031be61c6b0a14265251c48bc5a8eddf8596d3/charts/hlf-peer/values.yaml) one?

Also, which are the yaml files for the configuration of the peers, orderer etc?

**Comment by dviejokfs** [comment]
Hi @nkaramolegos 
Those values are used for the internal helm chart that is used by the operator, and these values are just the default ones, the real ones are set in the operator.

The operator parameters are specified with a CRD, for example, this would be a CRD used to deploy a peer:
```yaml
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricPeer
metadata:
  labels:
    dc: dc1
    mspID: KFSMSP
  name: peer0-kfsmsp
  namespace: hlf
spec:
  couchDBexporter:
    enabled: true
    image: gesellix/couchdb-prometheus-exporter
    imagePullPolicy: IfNotPresent
    tag: v30.0.0
  couchdb:
    password: couchdb
    user: couchdb
  discovery:
    period: 60s
    touchPeriod: 60s
  dockerSocketPath: ''
  externalBuilders:
    - name: external-builder
      path: /builders/external-service
      propagateEnvironment: []
    - name: external-k8s-builder
      path: /builders/golang
      propagateEnvironment:
        - CHAINCODE_SHARED_DIR
        - FILE_SERVER_BASE_IP
        - KUBERNETES_SERVICE_HOST
        - KUBERNETES_SERVICE_PORT
        - K8SCC_CFGFILE
        - TMPDIR
        - LD_LIBRARY_PATH
        - LIBPATH
        - PATH
        - EXTERNAL_BUILDER_HTTP_PROXY
        - EXTERNAL_BUILDER_HTTPS_PROXY
        - EXTERNAL_BUILDER_NO_PROXY
        - EXTERNAL_BUILDER_PEER_URL
  externalEndpoint: 'peer0.company.io:443'
  external_chaincode_builder: true
  gossip:
    bootstrap: ''
    endpoint: 'peer0.company.io:443'
    externalEndpoint: 'peer0.company.io:443'
    orgLeader: true
    useLeaderElection: false
  hosts:
    - peer0.company.io
  image: ghcr.io/kfsoftware/peer
  imagePullPolicy: IfNotPresent
  istio:
    hosts:
      - peer0.company.io
    ingressGateway: ''
    port: 443
  logging:
    cauthdsl: info
    gossip: info
    grpc: info
    ledger: info
    level: info
    msp: info
    peer: info
    policies: info
  mspID: KFSMSP
  replicas: 1
  resources:
    chaincode:
      limits:
        cpu: 100m
        memory: 56Mi
      requests:
        cpu: 10m
        memory: 28Mi
    couchdb:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
    peer:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 256Mi
  secret:
    enrollment:
      component:
        cahost: ca.company.io
        caname: ca
        caport: 443
        catls:
          cacert: >-
            <BASE64 TLS CERT OF THE CA>
        enrollid: peer
        enrollsecret: peerpw
      tls:
        cahost: ca.company.io
        caname: tlsca
        caport: 443
        catls:
          cacert: >-
            <BASE64 TLS CERT OF THE CA>
        csr:
          cn: peer0-company
          hosts:
            - 127.0.0.1
            - localhost
            - peer0.company.io
        enrollid: peer
        enrollsecret: peerpw
  service:
    type: NodePort
  serviceMonitor:
    enabled: true
    interval: 10s
    labels: {}
    sampleLimit: 0
    scrapeTimeout: 10s
  stateDb: couchdb
  storage:
    chaincode:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: default
    couchdb:
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: default
    peer:
      accessMode: ReadWriteOnce
      size: 4Gi
      storageClass: default
  tag: v2.3.0-0.0.1

```

This is what the kubectl plugin creates in the cluster behind the scenes.

Note that in this case, the yaml specifies the stateDB in L126:
```yaml
  stateDb: couchdb
```
