### ISSUE TITLE
[Peer] Schema not applied correctly?

### ISSUE THREAD

**Issue by rrozek** [kfsoftware/hlf-operator#78]
When deploying CA i can pass `spec.hosts` list for the list of hosts i want my ca to be visible at. Passing the same structure to peer deployment throws istio error.
```
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricPeer
...
  hostAliases: null
  hosts:
  - localhost
  - org1-peer0-channel0
  - org1-peer0-channel0.namespace1
  image: quay.io/kfsoftware/fabric-peer
  tag: 2.3.0-v0.0.2
  imagePullPolicy: Always
  istio:
    ingressGateway: ingressgateway
    port: 443
...
```
result:
`kubectl --namespace=namespace1 describe fabricpeers.hlf.kungfusoftware.es org1-peer0-channel0`
```
unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
```

Am i doing something wrong or is it a bug in plugin/operator?
When i pass the default `hosts: []`, then deploy the peer and then alter the `spec.hosts` and reapply it seems to work but haven't yet verified if i can actually use names instead of IPs to connect to peers.
